version: "2"
services:
  node:
    image: "node:12"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - 5000:3000
    command: >
      bash -c "yarn run dev"

